### ISSUE TITLE
thoughts on having a release package people can get without setting up python env?

### ISSUE THREAD

**Issue by cktang88** [QiuYannnn/Local-File-Organizer#10]

**Comment by webbrowser11** [comment]
i think you would have to have a python environment set up to access the python package manager. (and run the code)

**Comment by nigelp** [comment]
whatever makes it easier to install/use gets my vote

**Comment by QiuYannnn** [comment]
As for the use, I recommend you to use [nexa cli-reference](https://github.com/NexaAI/nexa-sdk/tree/main?tab=readme-ov-file#cli-reference) I will pass along your feedback about installation to the Nexa SDK team. You can also submit any questions or inquiries directly [here](https://github.com/NexaAI/nexa-sdk/tree/main).
