### ISSUE TITLE
Issue with pyrealine3 in Windows Command Prompt

### ISSUE THREAD

**Issue by joaoppadua** [QiuYannnn/Local-File-Organizer#12]
Hi, 
I ran into a problem with trying the script in a Windows Command Prompt. 
The pyreadline3 library was returning an error in determining the size of the console. 
I was able to fix it, by substituting the `input()` function with the `sys.stdin.readline()` method. 
I'm not making a pull request, as I don't know if this is a recurrent issue. 
If you want me to do it, please let me know.
Best, 
Joao

**Comment by CognitiveTwo** [comment]
Please commit. 
Am getting a
TypeError: cannot unpack non-iterable NoneType object
Input path  does not exist. Please create it and add the necessary files.

and debugging with ChatGPT also pointed to the pyreadline3 library t cause issues

**Comment by QiuYannnn** [comment]
It should be SDK problem about Window, please leave the question in [Nexa SDK Issue Tab](https://github.com/NexaAI/nexa-sdk/issues)
