### ISSUE TITLE
WIndows: punkt_tab not found

### ISSUE THREAD

**Issue by l3if3rik** [QiuYannnn/Local-File-Organizer#17]
I followed the instructions and installed everything. Program runs fine first, but after reading a JPG, it ends with:

```
 Resource punkt_tab not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('punkt_tab')

  For more information see: https://www.nltk.org/data.html

  Attempted to load tokenizers/punkt_tab/english/
```

Side note: I also had to install matplotlib,

**Comment by l3if3rik** [comment]
This can be closed. I expected this to be a hint for the developer to use `import nltk` etc.
But I ran this in a python repl and even got a nice GUI for downloading stuff.

**Comment by QiuYannnn** [comment]
I think I have written the code to download the nltk directly [link](https://github.com/QiuYannnn/Local-File-Organizer/blob/main/main.py#L29), it won't have the error I think
