### ISSUE TITLE
lost progress

### ISSUE THREAD

**Issue by Ysf101** [QiuYannnn/Local-File-Organizer#19]
if anything happens to the process of organizing the progress is lost

**Comment by QiuYannnn** [comment]
Based on previous user feedback, many users felt lost while loading files. Therefore, I added a progress indicator specifically for file processing. Since file categorization is a quick process once the files are analysis, I didn't include a progress bar for that step.

**Comment by Ysf101** [comment]
sorry for my bad explanation, i mean the whole process not just organizing one file for example when I hit control+C i expect to have a message asking if i want to stop where i'm and save the output instead i get an error message and the whole progress up to that point is lost
