### ISSUE TITLE
Renaming files might not be a good idea

### ISSUE THREAD

**Issue by Ysf101** [QiuYannnn/Local-File-Organizer#23]

**Comment by QiuYannnn** [comment]
Could you clarify your question a bit more? I'm not entirely sure I understand the issue you're describing.

**Comment by Ysf101** [comment]
sure, when organizing the files by content types the local file organizer automatically rename them which i think is not a good idea, it would be good if there was an option to select if the user wants to rename files or not.

**Comment by QiuYannnn** [comment]
Thank you for your feedback! I will add this option in future versions to give users more flexibility!
