### ISSUE TITLE
Support for video

### ISSUE THREAD

**Issue by mysticaltech** [QiuYannnn/Local-File-Organizer#3]
Hello @QiuYannnn, this is amazing!

If video could be added, it would be amazing. I would proposed to sample a few images and/or run whisper to extract the audio content. With both, one could infer what a video is all about too. 

Ideally this project would support any file and would iteratively build its own tools needed to get the job done and would even submit a PR on its own if it works well.

Also it makes me think of https://github.com/OpenInterpreter/aifs

Keep up the good work and thank you for sharing 🙏

**Comment by QiuYannnn** [comment]
Hi @mysticaltech, 

Thank you so much for your valuable feedback and suggestions! While I am still in the early stages of development, supporting a wider range of file formats is definitely part of our roadmap. 

As I continue with future iterations, I will work to incorporate these features to make the tool even more user-friendly and efficient.  I am excited to evolve the project with these improvements in mind.

Thank you again for sharing your thoughts and for your encouragement! 🙏

**Comment by mysticaltech** [comment]
Thank you @QiuYannnn
