### ISSUE TITLE
CPU/GPU usage limits

### ISSUE THREAD

**Issue by kaxlabs** [QiuYannnn/Local-File-Organizer#4]
Any way to add limits to how many resources are utilized during the sorting? My computer slows to nearly a stop while trying to use this.

**Comment by d1maz** [comment]
In `data_processing.py` file, there are 2 lines that look like this: `with Pool(cpu_count()) as pool:`.
If you change the part from `cpu_count()` to `cpu_count() / 2` then the program will use half of your available CPU threads.

These are the 2 mentioned lines:
1. https://github.com/QiuYannnn/Local-File-Organizer/blob/main/data_processing.py#L146
2. https://github.com/QiuYannnn/Local-File-Organizer/blob/main/data_processing.py#L234

Try it out.
