### ISSUE TITLE
Command line parameters & documentation update

### ISSUE THREAD

**Issue by vanhauser-thc** [QiuYannnn/Local-File-Organizer#6]
It would be great if the tool would support command line parameters instead of only questions on startup. this would also make the dry-run option easier I think.

> SDK Models:
The script uses NexaVLMInference and NexaTextInference models.
Ensure you have access to these models and they are correctly set up.
You may need to download model files or configure paths.

How do they need to be set up? this information does not help me to know what needs to be done. maybe a link to a place where this is described would help.

**Comment by QiuYannnn** [comment]
Thank you for your suggestion! I’ll be adding a `dry-run` mode in the next version, as it’s been the most requested feature. 

For more `NexaVLMInference` and `NexaTextInference` information on how to set it up and other details, you can refer to the [Nexa AI documentation](https://docs.nexaai.com/sdk/python-interface/gguf).

**Comment by vanhauser-thc** [comment]
The link sadly does not help me at all. do I need to download something? create a file? edit a file? which? where? the description there is very generic and how it applies to your project is unclear.
maybe it makes sense to someone who knows who do code with nexa ai - but to me (and I code quite some if you look at my profile) - it does not make me more knowledgeable how to solve this :)

**Comment by QiuYannnn** [comment]
I think you don't need to create or edit a file for VLM or Text inference. To download the desired model to fit Inference, I recommand you visit the [Nexa Model Hub](https://nexaai.com/models). If you're not familiar with SDK commands,  [Nexa SDK Reference](https://github.com/NexaAI/nexa-sdk/tree/main?tab=readme-ov-file#cli-reference) will be a helpful guidance. feel free to let me know if you have any more questions.
